### ISSUE TITLE
Logs are shown with weird symbols in Azure Release

### ISSUE THREAD

**Issue by leandroborgesca** [microsoft/azure-pipelines-terraform#84] opened 2022-08-22 10:43 UTC
When running Azure Releases  the log shows weird symbols in the agent log.

2022-08-22T10:32:48.9498187Z [33m│[0m [0m
2022-08-22T10:32:48.9498710Z [33m│[0m [0m[0mThe root module does not declare a variable named "web_linuxvm_admin_user"
2022-08-22T10:32:48.9499362Z [33m│[0m [0mbut a value was found in file "dev.tfvars". If you meant to use this value,
2022-08-22T10:32:48.9500262Z [33m│[0m [0madd a "variable" block to the configuration.
2022-08-22T10:32:48.9500848Z [33m│[0m [0m
2022-08-22T10:32:48.9501542Z [33m│[0m [0mTo silence these warnings, use TF_VAR_... environment variables to provide
2022-08-22T10:32:48.9502181Z [33m│[0m [0mcertain "global" settings to all configurations in your organization. To
2022-08-22T10:32:48.9502859Z [33m│[0m [0mreduce the verbosity of these warnings, use the -compact-warnings option.
2022-08-22T10:32:48.9503313Z [33m╵[0m[0m
2022-08-22T10:32:48.9503665Z [33m╷[0m[0m
2022-08-22T10:32:48.9504139Z [33m│[0m [0m[1m[33mWarning: [0m[0m[1mValue for undeclared variable[0m
2022-08-22T10:32:48.9504579Z [33m│[0m [0m
2022-08-22T10:32:48.9505096Z [33m│[0m [0m[0mThe root module does not declare a variable named "web_linuxvm_size" but a
2022-08-22T10:32:48.9505743Z [33m│[0m [0mvalue was found in file "dev.tfvars". If you meant to use this value, add a
2022-08-22T10:32:48.9506307Z [33m│[0m [0m"variable" block to the configuration.
2022-08-22T10:32:48.9506723Z [33m│[0m [0m
2022-08-22T10:32:48.9507255Z [33m│[0m [0mTo silence these warnings, use TF_VAR_... environment variables to provide
2022-08-22T10:32:48.9507887Z [33m│[0m [0mcertain "global" settings to all configurations in your organization. To
2022-08-22T10:32:48.9508933Z [33m│[0m [0mreduce the verbosity of these warnings, use the -compact-warnings option.

**Comment by mericstam** [comment] 2022-08-29 10:13
Hi, this a duplicate of #71.

**Closed by mericstam** 2022-08-29 10:13 UTC
