### ISSUE TITLE
Terraform init failure on Azure Devops Pipeline

### ISSUE THREAD

**Issue by WXRK** [microsoft/azure-pipelines-terraform#209] opened 2024-01-31 02:23 UTC
Dear gurus,

i have been working on fixing this issue with no luck and i hope i could have some advise here, thank you in advance.
I have a simple yaml file below:
==========================================================
 Starter pipeline
 Start with a minimal pipeline that you can customize to build and deploy your code.
 Add steps that build, run tests, deploy, and more:
 https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'

  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-AzureDevOps/TFAZDO'
      backendServiceArm: 'Azure subscription 1(1)(bf8d4281-83dd-42b3-b885-13278df4489f)'
      backendAzureRmResourceGroupName: 'AZTFDO-Storage'
      backendAzureRmStorageAccountName: 'aztfdostor'
      backendAzureRmContainerName: 'aztfdoblob'
      backendAzureRmKey: 'aztfdoblob.state'
  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'validate'
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-AzureDevOps/TFAZDO'
  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-AzureDevOps/TFAZDO'
      environmentServiceNameAzureRM: 'Azure subscription 1(bf8d4281-83dd-42b3-b885-13278df4489f)'

=============================================================

whenever i run the pipeline, the error fails during terraform init:

![image](https://github.com/microsoft/azure-pipelines-terraform/assets/154480601/39aa353e-343b-40a7-b28c-ea852261fbea)

/opt/hostedtoolcache/terraform/1.7.1/x64/terraform init -backend-config=storage_account_name=aztfdostor -backend-config=container_name=aztfdoblob -backend-config=key=aztfdoblob.state -backend-config=resource_group_name=AZTFDO-Storage -backend-config=subscription_id=bf8d4281-83dd-42b3-b885-13278df4489f -backend-config=tenant_id=ebd0b70e-75c8-4904-b36c-5979c95af1e2 -backend-config=client_id=*** -backend-config=client_secret=***
##[error]Error: There was an error when attempting to execute the process '/opt/hostedtoolcache/terraform/1.7.1/x64/terraform'. This may indicate the process failed to start. Error: spawn /opt/hostedtoolcache/terraform/1.7.1/x64/terraform ENOENT

Please can someone advise me where could i be wrong?

**Comment by dcarvalh04** [comment] 2024-01-31 16:02
Same error here with terraform 1.7.2

**Comment by jaredfholgate** [comment] 2024-02-01 11:54
> Dear gurus,
> 
> # i have been working on fixing this issue with no luck and i hope i could have some advise here, thank you in advance.
> I have a simple yaml file below:
> Starter pipeline Start with a minimal pipeline that you can customize to build and deploy your code. Add steps that build, run tests, deploy, and more: https://aka.ms/yaml
> 
> trigger: none
> 
> pool: vmImage: ubuntu-latest
> 
> steps:
> 
> * task: TerraformInstaller@1
>   inputs:
>   terraformVersion: 'latest'
> * task: TerraformTaskV4@4
>   inputs:
>   provider: 'azurerm'
>   command: 'init'
>   workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-AzureDevOps/TFAZDO'
>   backendServiceArm: 'Azure subscription 1(1)(bf8d4281-83dd-42b3-b885-13278df4489f)'
>   backendAzureRmResourceGroupName: 'AZTFDO-Storage'
>   backendAzureRmStorageAccountName: 'aztfdostor'
>   backendAzureRmContainerName: 'aztfdoblob'
>   backendAzureRmKey: 'aztfdoblob.state'
> * task: TerraformTaskV4@4
>   inputs:
>   provider: 'azurerm'
>   command: 'validate'
>   workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-AzureDevOps/TFAZDO'
> * task: TerraformTaskV4@4
>   inputs:
>   provider: 'azurerm'
>   command: 'apply'
>   workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-AzureDevOps/TFAZDO'
>   environmentServiceNameAzureRM: 'Azure subscription 1(bf8d4281-83dd-42b3-b885-13278df4489f)'
> 
> =============================================================
> 
> whenever i run the pipeline, the error fails during terraform init:
> 
> ![image](https://private-user-images.githubusercontent.com/154480601/301018504-39aa353e-343b-40a7-b28c-ea852261fbea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3ODgyNTYsIm5iZiI6MTcwNjc4Nzk1NiwicGF0aCI6Ii8xNTQ0ODA2MDEvMzAxMDE4NTA0LTM5YWEzNTNlLTM0M2ItNDBhNy1iMjhjLWVhODUyMjYxZmJlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMVQxMTQ1NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZWJjZTI1YWQ5ODhkMDZiNzRjNzk0MTM5MmY5NDE3YmUyMTk3NWNiNDgyYjcxYWQ0NWYwYWUwMDhmZDk5ZmYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bQZXNA3r2bTvPRLSrvmP_RQSMHD3Dx2orVA1F1XVbTU)
> 
> /opt/hostedtoolcache/terraform/1.7.1/x64/terraform init -backend-config=storage_account_name=aztfdostor -backend-config=container_name=aztfdoblob -backend-config=key=aztfdoblob.state -backend-config=resource_group_name=AZTFDO-Storage -backend-config=subscription_id=bf8d4281-83dd-42b3-b885-13278df4489f -backend-config=tenant_id=ebd0b70e-75c8-4904-b36c-5979c95af1e2 -backend-config=client_id=*** -backend-config=client_secret=*** ##[error]Error: There was an error when attempting to execute the process '/opt/hostedtoolcache/terraform/1.7.1/x64/terraform'. This may indicate the process failed to start. Error: spawn /opt/hostedtoolcache/terraform/1.7.1/x64/terraform ENOENT
> 
> Please can someone advise me where could i be wrong?

This is not an error I have seen before.

I see you are using different Service Connections for `init` and `apply`. Is that by design?

There is nothing obviously wrong with the init command shown. If you can trigger the pipeline with diagnostics set, it may provide more insights. You can also set the `TF_LOG` env var to `TRACE` if the issue is with the Terraform CLI. See here: https://developer.hashicorp.com/terraform/internals/debugging

**Comment by dcarvalh04** [comment] 2024-02-01 12:40
> Hi Dcarvalho and Jared, Thank you for replying. I am still newbie and self learning on terraform. so:
> 
> @dcarvalh04 could you elaborate further on the technical steps? @jaredfholgate it is not by design, i was just simply creating steps and thank you for spotting my mistake. I shall try to align them both.

I was having the same exact issue as you did, even tried a different ubuntu version and a different terraform version. The way I solved it is still mysterious since I haven't done much beside rewriting the yaml pipeline using the built-in UI instead of copy-pasting from the sample code:

![image](https://github.com/microsoft/azure-pipelines-terraform/assets/132361946/877f7602-70ae-457e-82ce-2f8d647defc9)

Using this "settings" I rewrote my whole config using the built-in editor and then it worked.
Either something wrong on my yaml copy paste either my variables...Can't tell for sure

**Comment by WXRK** [comment] 2024-02-05 06:52
i am still not having luck despite manually rewriting the terraform init command settings. Would you mind sharing your yaml file with me? (i might be asking too much).

**Comment by vedbharathi** [comment] 2024-07-08 02:31
Please help , i am also getting the same error.  do we have to specify the working directory where the terraform files are available?  when i run the command from the agent working directory where the terraform files are available , the command works all fine. but when i run through pipeline it is failing

      - task: TerraformTaskV4@4
        displayName: 'Terraform init'
        inputs:
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test/'
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'my connection'
          backendAzureRmResourceGroupName: 'rg'
          backendAzureRmStorageAccountName: 'tfstate'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'test.terraform.tfstate'

**Comment by jaredfholgate** [comment] 2024-07-08 07:59
> Please help , i am also getting the same error. do we have to specify the working directory where the terraform files are available? when i run the command from the agent working directory where the terraform files are available , the command works all fine. but when i run through pipeline it is failing
> 
> ```
>   - task: TerraformTaskV4@4
>     displayName: 'Terraform init'
>     inputs:
>       workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test/'
>       provider: 'azurerm'
>       command: 'init'
>       backendServiceArm: 'my connection'
>       backendAzureRmResourceGroupName: 'rg'
>       backendAzureRmStorageAccountName: 'tfstate'
>       backendAzureRmContainerName: 'tfstate'
>       backendAzureRmKey: 'test.terraform.tfstate'
> ```
Hi

There isn't much to go on here:

- What error are you getting? 
- What does your directory structure look like. 
- What do you mean by "when i run the command from the agent working directory where the terraform files are available , the command works all fine"? Are you saying it runs fine in the root of your source code where there is no Terraform module?

Thanks

**Comment by PullaiahDegala** [comment] 2024-07-09 18:47
> Dear gurus,
> 
> # i have been working on fixing this issue with no luck and i hope i could have some advise here, thank you in advance.
> I have a simple yaml file below:
> Starter pipeline Start with a minimal pipeline that you can customize to build and deploy your code. Add steps that build, run tests, deploy, and more: https://aka.ms/yaml
> 
> trigger: none
> 
> pool: vmImage: ubuntu-latest
> 
> steps:
> 
> * task: TerraformInstaller@1
>   inputs:
>   terraformVersion: 'latest'
> * task: TerraformTaskV4@4
>   inputs:
>   provider: 'azurerm'
>   command: 'init'
>   workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-AzureDevOps/TFAZDO'
>   backendServiceArm: 'Azure subscription 1(1)(bf8d4281-83dd-42b3-b885-13278df4489f)'
>   backendAzureRmResourceGroupName: 'AZTFDO-Storage'
>   backendAzureRmStorageAccountName: 'aztfdostor'
>   backendAzureRmContainerName: 'aztfdoblob'
>   backendAzureRmKey: 'aztfdoblob.state'
> * task: TerraformTaskV4@4
>   inputs:
>   provider: 'azurerm'
>   command: 'validate'
>   workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-AzureDevOps/TFAZDO'
> * task: TerraformTaskV4@4
>   inputs:
>   provider: 'azurerm'
>   command: 'apply'
>   workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-AzureDevOps/TFAZDO'
>   environmentServiceNameAzureRM: 'Azure subscription 1(bf8d4281-83dd-42b3-b885-13278df4489f)'
> 
> =============================================================
> 
> whenever i run the pipeline, the error fails during terraform init:
> 
> ![image](https://private-user-images.githubusercontent.com/154480601/301018504-39aa353e-343b-40a7-b28c-ea852261fbea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NDA0NTUsIm5iZiI6MTcyMDU0MDE1NSwicGF0aCI6Ii8xNTQ0ODA2MDEvMzAxMDE4NTA0LTM5YWEzNTNlLTM0M2ItNDBhNy1iMjhjLWVhODUyMjYxZmJlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxNTQ5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjcxNzFjNzgwN2E4MGYxZGM3ZjQ3Yjk3MzUxYWM5YjdkYjliZGY3YTUyMDlhYTAyZTk5Yzk4NGNlNDkzOWNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0sRYnx3b8uGEOuRZBWwAG0D5pDBc5VTGZeo1F3AVg50)
> 
> /opt/hostedtoolcache/terraform/1.7.1/x64/terraform init -backend-config=storage_account_name=aztfdostor -backend-config=container_name=aztfdoblob -backend-config=key=aztfdoblob.state -backend-config=resource_group_name=AZTFDO-Storage -backend-config=subscription_id=bf8d4281-83dd-42b3-b885-13278df4489f -backend-config=tenant_id=ebd0b70e-75c8-4904-b36c-5979c95af1e2 -backend-config=client_id=*** -backend-config=client_secret=*** ##[error]Error: There was an error when attempting to execute the process '/opt/hostedtoolcache/terraform/1.7.1/x64/terraform'. This may indicate the process failed to start. Error: spawn /opt/hostedtoolcache/terraform/1.7.1/x64/terraform ENOENT
> 
> Please can someone advise me where could i be wrong?



"I am facing the same problem. Could you please provide guidance on resolving it?"

**Comment by jmlp1** [comment] 2024-07-20 15:31
has anyone found a solution for this yet? I am having issues with my own version, pretty similar to the ones shown here, same issue init breaks "backendServiceArm" no found and it is exactly as the one setup, all pipes having permissions to it, it's driving me crazy

**Closed** 2024-07-22 08:14 UTC

**Comment by jantzen05** [comment] 2024-08-02 08:32
Running on Azure DevOps with ubuntu-latest image.

Full yaml file:
[azure-infrastructure.txt](https://github.com/user-attachments/files/16467514/azure-infrastructure.txt)

Service connection:
![ServiceConnection](https://github.com/user-attachments/assets/47831e27-feeb-44c8-8caa-fb026a5d214a)

Folder structure:
Project folder
- .ado
- terraform
-- variables
![terraformFolder](https://github.com/user-attachments/assets/dc27a683-cf39-4599-9920-9636e2b7fa20)

What I see is that between stages the terraform version changes and if you transfer the plan file between then it fails.
![image](https://github.com/user-attachments/assets/ea6c49d7-6068-4e4f-bf90-5ad37a641f71)

Errors
> │ Error: Failed to read plan from plan file
│ Cannot read the plan from the given plan file: plan file was created by
│ Terraform 1.9.2, but this is 1.9.3; plan files cannot be transferred
│ between different Terraform versions.

or

> │ Error: Failed to read plan from plan file
│ Cannot read the plan from the given plan file: plan file was created by
│ Terraform 1.9.3, but this is 1.9.2; plan files cannot be transferred
│ between different Terraform versions.

**Comment by jaredfholgate** [comment] 2024-08-02 13:56
> Running on Azure DevOps with ubuntu-latest image.
> 
> Full yaml file: [azure-infrastructure.txt](https://github.com/user-attachments/files/16467514/azure-infrastructure.txt)
> 
> Service connection: ![ServiceConnection](https://private-user-images.githubusercontent.com/7024463/354521014-47831e27-feeb-44c8-8caa-fb026a5d214a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MDY5MjYsIm5iZiI6MTcyMjYwNjYyNiwicGF0aCI6Ii83MDI0NDYzLzM1NDUyMTAxNC00NzgzMWUyNy1mZWViLTQ0YzgtOGNhYS1mYjAyNmE1ZDIxNGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMTM1MDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjYxM2JiNTcyMjQwMzhjMjk2OTNjZDRhNDJhMGYzZmNlY2ZhZGRlOWJiZDI3NmZmZTU4MGI2Njg5YmZlYmI2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pFJ44W09Y7nhgD2hKHI4U0_yIztpnrJVJ6KpDbv0GPA)
> 
> Folder structure: Project folder
> 
> * .ado
> * terraform
>   -- variables
>   ![terraformFolder](https://private-user-images.githubusercontent.com/7024463/354522573-dc27a683-cf39-4599-9920-9636e2b7fa20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MDY5MjYsIm5iZiI6MTcyMjYwNjYyNiwicGF0aCI6Ii83MDI0NDYzLzM1NDUyMjU3My1kYzI3YTY4My1jZjM5LTQ1OTktOTkyMC05NjM2ZTJiN2ZhMjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMTM1MDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmM0MGYwODdjNTQ5ZGIxM2Q3NDYzMjQ3ZWU1YWE2ZTU4OTIwNzllOTk4OTgzZjZhZWE5OGU5OWNhZTZlM2RmYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LNg8NYYAGWwblvV7S2Mv1hKUEL_lrBL-1zOrEELqMlY)
> 
> What I see is that between stages the terraform version changes and if you transfer the plan file between then it fails. ![image](https://private-user-images.githubusercontent.com/7024463/354527592-ea6c49d7-6068-4e4f-bf90-5ad37a641f71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MDY5MjYsIm5iZiI6MTcyMjYwNjYyNiwicGF0aCI6Ii83MDI0NDYzLzM1NDUyNzU5Mi1lYTZjNDlkNy02MDY4LTRlNGYtYmY5MC01YWQzN2E2NDFmNzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMTM1MDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2RhNzMwYmE2MDY5Y2E2NjM2YWFiNDg0YjYxNTE4ODRmOTc4OGRlMDljZDRjMzMzNzM2NTg0Y2JjZmVkNjk3NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GBkranZoYzg6c3M1tIBBK6gmrf3EJrMsrJ3aRRiEelo)
> 
> Errors
> 
> > │ Error: Failed to read plan from plan file
> > │ Cannot read the plan from the given plan file: plan file was created by
> > │ Terraform 1.9.2, but this is 1.9.3; plan files cannot be transferred
> > │ between different Terraform versions.
> 
> or
> 
> > │ Error: Failed to read plan from plan file
> > │ Cannot read the plan from the given plan file: plan file was created by
> > │ Terraform 1.9.3, but this is 1.9.2; plan files cannot be transferred
> > │ between different Terraform versions.

Hi. This error is unrelated to this issue. This can happen when a new agent version is being rolled out. I recommend adding a Terraform Install task step and specifying latest or a pinned version to ensure you have same version on all job runs.

**Comment by jaredfholgate** [comment] 2025-10-29 17:52
> i have this error, any one can help me?
> 
>   | Error: There was an error when attempting to execute the process 'C:\agent_work_tool\terraform\1.13.4\x64\terraform.exe'. This may indicate the process failed to start. Error: spawn C:\agent_work_tool\terraform\1.13.4\x64\terraform.exe ENOENTTerraformTaskV4

Hi @Najib-Hebrawi. Commenting on an issue that was closed over a year ago is not the recommended way to get help.

If you believe this is a bug on the task, try opening a new issue and provide a reproduction of you problem. E.g. what agent you are using, your pipeline code, etc. 

Thanks
